# This is a basic workflow to help you get started with Actions

name: Scan-Credentials

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pip install virtualenv
          virtualenv venv
          chmod +x venv/bin/activate
          source venv/bin/activate
          pip install --upgrade trufflehog3
          trufflehog3 --format=json --skip-paths venv -- .

